apiVersion: apps/v1
kind: Deployment
metadata:
  name: emea8-squad2-telp
  annotations:
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea8-squad2-TELP
    app.openshift.io/vcs-ref: 3e007beb70ae1b16c078a7ace1e0a5961e20a7d5
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: app-instance
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: app-instance
        app.kubernetes.io/name: app
    spec:
      containers:
        - name: emea8-squad2-telp
          image: quay.io/pbworker/telp-app:3e007beb70ae1b16c078a7ace1e0a5961e20a7d5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
